name: Sync

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Build Gitee Pages
      uses: xingwumo/gitee-pages-action@main
      with:
        # 注意替换为你的 Gitee 用户名
        gitee-username: xingwumo
        # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
        gitee-password: ${{ secrets.GITEE_PASSWORD }}
        # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错。如果你的Gitee 的地址为 https://gitee.com/用户名/xxx ，那么 gitee-repo 就填写为 用户名/xxx。
        gitee-repo: xingwumo/blog
        # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
        branch: master